### ISSUE TITLE
RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([1]) and output[0] has a shape of torch.Size([]).

### ISSUE THREAD

**Issue by Tylersuard** [fancoo/WaveGAN-pytorch#9]
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    D_real.backward(neg_one)  # loss * -1
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 93, in backward
    grad_tensors = _make_grads(tensors, grad_tensors)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 29, in _make_grads
    + str(out.shape) + ".")
RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([1]) and output[0] has a shape of torch.Size([]).

**Comment by DWhettam** [comment]
Any luck with this issue? I've tried training on the piano data and I'm getting the same issue. I'm running on a cluster so not able to put the training data in the same directory as the code, but I've specified the directory in args.audio_dir

**Comment by DWhettam** [comment]
**Resolved:** 
change `one = torch.Tensor([1]).float()` to `one = torch.tensor(1, dtype=torch.float)` on line 104.

I also had to change to change the print statement on line 213 to do non-integer division: 
`if i % (BATCH_NUM / 5) == 0:`

**Comment by mazzzystar** [comment]
Hi, sorry for the late response.
The implementation was done in 2018, so I think this should be PyTorch version issue.

**Comment by sandip-baidya** [comment]
Hey, the fix worked
but all the samples generated after training don't carry any sounds at all. I don't know why that's happening. Was there a problem during converting them from numpy arrays to .wav files?
